document.addEventListener('DOMContentLoaded',()=>{
  const run=document.getElementById('anjod-run'),out=document.getElementById('anjod-progress');
  async function call(action){const body=new URLSearchParams({action,nonce:anjodImport.nonce});const response=await fetch(anjodImport.url,{method:'POST',credentials:'same-origin',body});const result=await response.json();if(!result.success)throw new Error(typeof result.data==='string'?result.data:'処理できませんでした。');return result.data;}
  run.addEventListener('click',async()=>{run.disabled=true;try{let r;do{r=await call('anjod_import');out.textContent=`${r.offset} / ${r.total} 件を処理済み（公開店舗 ${r.published} 件）`;}while(!r.done);out.textContent+='：取り込み完了';}catch(e){out.textContent='停止しました：'+e.message+' 「開始・再開」で続きから取り込めます。';}finally{run.disabled=false;}});
  const page=document.getElementById('anjod-page');page.addEventListener('click',async()=>{page.disabled=true;const target=document.getElementById('anjod-page-result');try{const r=await call('anjod_page');const a=document.createElement('a');a.href=r.url;a.textContent='安城ナビの検索ページを開く';target.replaceChildren(a);}catch(e){target.textContent=e.message;}finally{page.disabled=false;}});
  const fixStatus=document.getElementById('anjod-fix-status');fixStatus.addEventListener('click',async()=>{fixStatus.disabled=true;const target=document.getElementById('anjod-fix-status-result');try{const r=await call('anjod_fix_status');target.textContent=`${r.updated}件を修正しました。`;}catch(e){target.textContent=e.message;}finally{fixStatus.disabled=false;}});
  const fixSource=document.getElementById('anjod-fix-source'),srcOut=document.getElementById('anjod-fix-source-progress');
  fixSource.addEventListener('click',async()=>{fixSource.disabled=true;let total=0;try{let r;do{r=await call('anjod_fix_source');total+=r.updated;srcOut.textContent=`${r.offset} / ${r.total} 件を確認済み（更新 ${total} 件）`;}while(!r.done);srcOut.textContent+='：反映完了';}catch(e){srcOut.textContent='停止しました：'+e.message+' 「反映・再開」で続きから実行できます。';}finally{fixSource.disabled=false;}});
  const fixFloor=document.getElementById('anjod-fix-floor'),floorOut=document.getElementById('anjod-fix-floor-progress');
  fixFloor.addEventListener('click',async()=>{fixFloor.disabled=true;let total=0;try{let r;do{r=await call('anjod_fix_floor');total+=r.updated;floorOut.textContent=`${r.offset} / ${r.total} 件を確認済み（更新 ${total} 件）`;}while(!r.done);floorOut.textContent+='：反映完了';}catch(e){floorOut.textContent='停止しました：'+e.message+' 「反映・再開」で続きから実行できます。';}finally{fixFloor.disabled=false;}});
});
